from datetime import datetime

AUTHOR = "Tai D. Nguyen"
ORCID = "0009-0005-3814-7192"
SYSTEM = "RID-UFE (Information–Dynamical Field Engine)"


def _f(x):
    try:
        return float(x)
    except:
        return 0.0


def generate_paper(exp_id, m):

    vol = _f(m.get("volatility"))
    ent = _f(m.get("entropy"))
    rand = _f(m.get("random_entropy"))
    spec = _f(m.get("spectral_gap"))
    corr = _f(m.get("curvature_future_vol_corr"))
    p = _f(m.get("entropy_p"))

    signal = abs(corr)

    if signal < 0.1:
        signal_level = "NO SIGNAL"
    elif signal < 0.2:
        signal_level = "WEAK SIGNAL"
    elif signal < 0.4:
        signal_level = "MODERATE SIGNAL"
    else:
        signal_level = "STRONG SIGNAL"

    randomness = "HIGHLY RANDOM" if ent > rand else "STRUCTURED SYSTEM"

    return f"""
# RID-UFE INFORMATION FIELD REPORT

---

## AUTHOR INFORMATION

- Author: {AUTHOR}
- ORCID: {ORCID}
- System: {SYSTEM}
- Experiment ID: {exp_id}
- Generated: {datetime.utcnow().isoformat()}

---

## ABSTRACT (Human-readable)

This report analyzes Bitcoin market behavior as an information field system.

Instead of treating price as random noise, RID-UFE models it as:
- structured information dynamics
- curvature-based predictive signals
- entropy-driven uncertainty fields

---

## 1. RAW METRICS

- Volatility: {vol:.6f}
- Entropy: {ent:.6f}
- Random Entropy: {rand:.6f}
- Spectral Gap: {spec:.6f}
- Curvature–Future Vol Correlation: {corr:.6f}
- P-value: {p:.6f}

---

## 2. SYSTEM STATE ANALYSIS

- Signal Level: {signal_level}
- Information Structure: {randomness}
- Market Regime: {"STABLE" if vol < 0.002 else "VOLATILE"}

---

## 3. SCIENTIFIC INTERPRETATION

The system indicates:

- Market is NOT fully random
- There exists weak-to-moderate structured information
- Predictive signal is limited but measurable

Entropy comparison suggests:
- system is {'ordered' if ent < rand else 'mixed/random-dominant'}

---

## 4. INSIGHT SUMMARY

→ Market regime: information-driven stochastic system  
→ Signal strength: {signal_level}  
→ Structural clarity: {randomness}  

---

## 5. CONCLUSION

This experiment suggests that Bitcoin price dynamics:

- contain weak emergent structure
- are partially predictable in curvature space
- remain dominated by stochastic noise

---

Generated by:
{SYSTEM}
Author: {AUTHOR} ({ORCID})
"""
