from datetime import datetime

AUTHOR = "Tai D. Nguyen"
ORCID = "0009-0005-3814-7192"
SYSTEM = "RID-UFE (Information–Dynamical Field Engine)"


def _f(x):
    try:
        return float(x)
    except:
        return 0.0


def generate_paper(exp_id, m, evidence=None):
    evidence = evidence or {}

    # Basic metrics
    raw = evidence.get("raw_metrics", {})

    vol = raw.get("volatility", m.get("volatility"))
    ent = raw.get("entropy", m.get("entropy"))
    autocorr = raw.get("autocorrelation", m.get("autocorrelation"))
    structure = raw.get(
        "structure_signal",
        m.get("structure_signal")
    )

    # Validation evidence
    corr = raw.get(
        "curvature_future_vol_correlation",
        evidence.get("observed_association")
    )
    p = raw.get(
        "permutation_p_value",
        evidence.get("null_p_value_two_sided")
    )
    train_corr = evidence.get("train_association")
    test_corr = evidence.get("test_association")

    predictive_claim = evidence.get(
        "predictive_claim",
        "NOT_ESTABLISHED"
    )

    causal_claim = evidence.get(
        "causal_claim",
        "NOT_ESTABLISHED"
    )

    # Raw validation metrics
    rand = raw.get(
        "random_entropy",
        evidence.get("random_entropy")
    )
    spec = raw.get(
        "spectral_gap",
        evidence.get("spectral_gap")
    )

    def fmt(x):
        if x is None:
            return "NOT_ESTIMATED"
        return f"{float(x):.6f}"

    # Conservative interpretation
    if structure is None:
        signal_level = "NOT_ESTIMATED"
    elif abs(structure) < 1e-4:
        signal_level = "WEAK"
    elif abs(structure) < 1e-3:
        signal_level = "WEAK_HEURISTIC"
    else:
        signal_level = "HIGH"

    if ent is None:
        randomness = "NOT_ESTIMATED"
    elif ent > 2.5:
        randomness = "HIGH-ENTROPY"
    elif ent > 1.5:
        randomness = "MIXED"
    else:
        randomness = "LOW-ENTROPY"

    if vol is None:
        regime = "NOT_ESTIMATED"
    elif vol < 0.002:
        regime = "STABLE"
    else:
        regime = "VOLATILE"

    if predictive_claim == "SUPPORTED_FOR_FURTHER_TESTING":
        predictive_text = (
            "The observed association passes the current "
            "validation criteria and is retained for further testing."
        )
    else:
        predictive_text = (
            "The current validation does not establish "
            "an out-of-sample predictive relationship."
        )

    if corr is None:
        association_text = "NOT_ESTIMATED"
    else:
        association_text = f"{float(corr):.6f}"

    return f"""
# RID-UFE Research Experiment

Experiment ID: {exp_id}

---

## 1. RAW METRICS

- Volatility: {fmt(vol)}
- Entropy: {fmt(ent)}
- Autocorrelation: {fmt(autocorr)}
- Structure Signal: {fmt(structure)}
- Random Entropy: {fmt(rand)}
- Spectral Gap: {fmt(spec)}
- Curvature–Future Volatility Association: {association_text}
- Validation P-value: {fmt(p)}

---

## 2. SYSTEM STATE ANALYSIS

- Signal Level: {signal_level}
- Information Structure: {randomness}
- Market Regime: {regime}

---

## 3. VALIDATION STATUS

- Observed Association: {association_text}
- Train Association: {fmt(train_corr)}
- Test Association: {fmt(test_corr)}
- Predictive Claim: {predictive_claim}
- Causal Claim: {causal_claim}

{predictive_text}

The reported association is statistical/temporal association only.
It should not be interpreted as evidence of causality.

---

## 4. SCIENTIFIC INTERPRETATION

The current experiment provides a quantitative description of
the constructed information-dynamical representation.

The similarity graph, spectral representation, and curvature
functional are mathematical constructions applied to the input
time series. They should not be interpreted as direct measurements
of physical spacetime curvature or a causal market mechanism.

The current validation result does not establish a robust
out-of-sample predictive relationship.

---

## 5. INSIGHT SUMMARY

- Market regime: {regime}
- Signal strength: {signal_level}
- Structural descriptor: {randomness}
- Predictive status: {predictive_claim}

---

## 6. CONCLUSION

This experiment identifies a measurable temporal association
between the constructed information-curvature descriptor and
future volatility.

However, the current evidence is insufficient to establish
a stable predictive effect or causal relationship.

Further evaluation should include additional time periods,
multiple assets, alternative null models, and strict
out-of-sample validation.

---

Generated by:
{SYSTEM}

Author: {AUTHOR} ({ORCID})
"""


    raw = evidence.get("raw_metrics", {})

    vol = _f(raw.get("volatility", m.get("volatility")))
    ent = _f(raw.get("entropy", m.get("entropy")))
    rand = _f(raw.get(
        "random_entropy",
        evidence.get("random_entropy")
    ))
    spec = _f(raw.get(
        "spectral_gap",
        evidence.get("spectral_gap")
    ))
    corr = _f(raw.get(
        "curvature_future_vol_correlation",
        evidence.get("observed_association")
    ))
    p = _f(raw.get(
        "permutation_p_value",
        evidence.get("null_p_value_two_sided")
    ))

    signal = abs(corr)

    if signal < 0.1:
        signal_level = "NO SIGNAL"
    elif signal < 0.2:
        signal_level = "WEAK SIGNAL"
    elif signal < 0.4:
        signal_level = "MODERATE SIGNAL"
    else:
        signal_level = "STRONG SIGNAL"

    randomness = "HIGHLY RANDOM" if ent > rand else "STRUCTURED SYSTEM"

    return f"""
# RID-UFE INFORMATION FIELD REPORT

---

## AUTHOR INFORMATION

- Author: {AUTHOR}
- ORCID: {ORCID}
- System: {SYSTEM}
- Experiment ID: {exp_id}
- Generated: {datetime.utcnow().isoformat()}

---

## ABSTRACT (Human-readable)

This report analyzes Bitcoin market behavior as an information field system.

Instead of treating price as random noise, RID-UFE models it as:
- structured information dynamics
- curvature-based predictive signals
- entropy-driven uncertainty fields

---

## 1. RAW METRICS

- Volatility: {vol:.6f}
- Entropy: {ent:.6f}
- Random Entropy: {rand:.6f}
- Spectral Gap: {spec:.6f}
- Curvature–Future Vol Correlation: {corr:.6f}
- P-value: {p:.6f}

---

## 2. SYSTEM STATE ANALYSIS

- Signal Level: {signal_level}
- Information Structure: {randomness}
- Market Regime: {"STABLE" if vol < 0.002 else "VOLATILE"}

---

## 3. SCIENTIFIC INTERPRETATION

The system indicates:

- Market is NOT fully random
- There exists weak-to-moderate structured information
- Predictive signal is limited but measurable

Entropy comparison suggests:
- system is {'ordered' if ent < rand else 'mixed/random-dominant'}

---

## 4. INSIGHT SUMMARY

→ Market regime: information-driven stochastic system  
→ Signal strength: {signal_level}  
→ Structural clarity: {randomness}  

---

## 5. CONCLUSION

This experiment suggests that Bitcoin price dynamics:

- contain weak emergent structure
- are partially predictable in curvature space
- remain dominated by stochastic noise

---

Generated by:
{SYSTEM}
Author: {AUTHOR} ({ORCID})
"""
