
def generate_report(exp_id, metrics, path):

    text = f"""
# RID-UFE Information Field Report

Experiment: {exp_id}

## Metrics

{metrics}

## Conclusion

This report is generated by RID-UFE research engine.
"""

    with open(path, "w") as f:
        f.write(text)
